### ISSUE TITLE
[10] password_security: on login ,odoo KeyError: 'login_success'

### ISSUE THREAD

**Issue by lonelyleaves** [OCA/server-tools#1081]
When I install this module, I will often prompt "500: Internal Server Error" when landing. Odoo's log shows KeyError:'login_success'.

**Comment by pedrobaeza** [comment]
We need steps to reproduce the error.

**Comment by lonelyleaves** [comment]
I can't find the rules，Super user accounts are normal, and ordinary users are very easy to appear
error code：
![image](https://user-images.githubusercontent.com/16489920/33509724-18f0054c-d73f-11e7-9620-6c4fd7ee06ca.png)

**Comment by pedrobaeza** [comment]
@lasley any clue?

**Comment by lasley** [comment]
Hmmm it looks like the request parameters aren't being preserved. It should be an easy fix, but I wonder what's causing it. Is this maybe on refreshing the page?

**Comment by lasley** [comment]
@lonelyleaves - please update your code. Current v10 already contains this fix

https://github.com/OCA/server-tools/pull/996

**Comment by lonelyleaves** [comment]
ok thks

**Comment by lonelyleaves** [comment]
I've updated the latest code, and I find it still often prompted by KeyError:'login_success'

**Comment by lonelyleaves** [comment]
![qq 20171220121026](https://user-images.githubusercontent.com/16489920/34190958-b35f195e-e57e-11e7-830c-7f348089e72a.png)

**Comment by lasley** [comment]
@lonelyleaves - what exactly do you have to do in order to make this error appear?

**Comment by lonelyleaves** [comment]
Open the home page, clicking on the landing will appear, I need to keep refreshing, odoo can appear normal landing interface

**Comment by lasley** [comment]
@lonelyleaves - sorry, I don't understand the process. Screenshots maybe?

**Comment by lonelyleaves** [comment]
can you install teamviewer?or I can be remotely  or email send video to you ！
If I uninstall this function, this will not happen.

**Comment by chris001** [comment]
@lonelyleaves 
Can you record your screen with this chrome extension, and share on youtube:
https://chrome.google.com/webstore/detail/screencastify-screen-vide/mmeijimgabbpbgpdklnllpncmdofkcpn?hl=en

**Comment by lonelyleaves** [comment]
I have send email to lasley  (dave@laslabs.com) ,can you see?that's ok？

**Comment by lasley** [comment]
@lonelyleaves - I received a rar file, but I do not make a habit of opening random binary files sent to me from the internet. 

Posting on YouTube and providing us the link here, [as @chris001 suggested](https://github.com/OCA/server-tools/issues/1081#issuecomment-353712093), is the best method of relaying this info. Additionally, this will allow all contributors to assist instead of just me. I may have made the addon, but it's community supported unless you have a support contract with LasLabs (my company).

**Comment by lonelyleaves** [comment]
ok thanks
I've put the video files on youtobe, thank you.，This is the url address
https://youtu.be/U7qkGtg10uc

**Comment by chris001** [comment]
@lonelyleaves 
"This video is unavailable" 😦

**Comment by lonelyleaves** [comment]
I've changed it to everyone.

**Comment by lonelyleaves** [comment]
https://github.com/thinkopensolutions/tko-addons/tree/10.0/tko_web_sessions_management
I'm not sure whether the conflict with this function has led to this situation.

**Comment by lasley** [comment]
@lonelyleaves - I assert the same thing I did previously - [this error is fixed in new code](https://github.com/OCA/server-tools/issues/1081#issuecomment-348655687). It is impossible for you to receive this traceback using the current code. Please update your code.

**Comment by lonelyleaves** [comment]
i have update code,but have not fixed 
![image](https://user-images.githubusercontent.com/16489920/34386240-ac8a3476-eb62-11e7-9f08-811ca8bc08f9.png)

**Comment by lasley** [comment]
@lonelyleaves - you have a different traceback then. Your traceback literally shows a line of code that no longer exists, and does not exist in your screenshot.

**Comment by lasley** [comment]
I'm assuming your new traceback was failing at the `request.session.authenticate` step below the original one. #1109 and #1108 make it so that line is never hit.
