### ISSUE TITLE
[16.0] Can't use base_fontawesome, not showing icons

### ISSUE THREAD

**Issue by iggups** [OCA/server-tools#2694]
## Module
base_fontawesome

## Describe the bug
Tried to use the new icons in an XML view but I don't see any icon at all. Maybe I am using it wrong? I followed the documentation.

## To Reproduce
**Affected versions**: 16.0.5.15.4

1. Install module
2. Add `<button brand_icon="fa-amazon-pay" string=" fa-amazon-pay"/>` to a form view
3. Only string is shown, no icon

**Expected behavior**
Icon is shown

**Comment by danielduqma** [comment]
Found similar bug, an easy way to reproduce is installing just `base_fontawesome` and `website` on a clean installation, for example on [runboat](http://oca-server-tools-16-0-3a5305184a8e.runboat.odoo-community.org/). Tested on linked runboat and right after installation icons of social networks on footer are broken:

  ![image](https://github.com/OCA/server-tools/assets/6009746/7f7f1f4e-2a95-4c4e-b7df-ca90a4c22495)

Looks like not all assets are loaded:

  ![image](https://github.com/OCA/server-tools/assets/6009746/3d61f6e9-a496-4acf-9108-65867b1800c9)

Could anyone take a look of this please @OCA/tools-maintainers?

Best regards.

**Comment by thomaspaulb** [comment]
It seems to be something amiss in [web.assets_frontend](https://github.com/OCA/server-tools/blob/3a5305184a8eb87ce60b7acaa0b0465b1e5f8afc/base_fontawesome/__manifest__.py#L25).

When inspecting `/web/assets/debug/1/web.assets_frontend.css` on Runboat, `fontawesome.css` is included, but `all.css` isn't, and I think that's the one needed for the correct interpretation of the `fa-*` classes. In the backend, it does work.

**Comment by danielduqma** [comment]
Solved in https://github.com/OCA/server-tools/pull/2740, could someone take a look please? Thanks!

**Comment by iggups** [comment]
Hi folks,
I am still not seeing the icons in the odoo backend. I am using them as described in the OP.

I updated the module to 16.0.5.16.0 and wanted to use the new icons in a form view button like:

```
<button class="oe_stat_button" type="object" name="action_foobar" brand_icon="fa-amazon-pay">
   <field name="foobar_count" widget="statinfo" string="Foo Bar"/>
</button>
```

**Comment by thomaspaulb** [comment]
@iggups I think it is now fixed

**Comment by iggups** [comment]
@thomaspaulb Unfortunately not.

This is my code:

```
<button class="oe_stat_button" type="object" name="action_external_contract"
                                brand_icon="fa-amazon-pay"
                        >
                            <field name="external_contract_count" widget="statinfo" string="External Contracts"/>
</button>
```

And this is how it looks
![Screenshot_20241015_082143](https://github.com/user-attachments/assets/c3de81e0-35b7-423d-9734-908278437c95)

I have the latest version intalled.
